services:
  jimmy:
    container_name: jimmy-v2
    build: .
    restart: unless-stopped
    tty: true
    volumes:
      - ./config.toml:/app/config.toml
      - ./jimmy.log:/app/jimmy.log
      - /dev/dri:/dev/dri
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - 11434:11434
    volumes:
      - ollama-data:/root/.ollama

volumes:
  ollama-data:

